version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET=jdsudkdsid5841645488151646jhudksdnkbsjcbdscds21c6ds4v6ds1vds15v4dsvndsdsoiods8789631450dcdudsnisasoduiypewfif
    volumes:
      - .:/usr/src/app
